name: Terraform Plan
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform_format_check:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  '${{ github.ref }}'
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform Format Check 
        id: fmt
        run: terraform fmt -check -recursive

  terraform_plan_develop:
    name: Terraform Plan Develop
    needs: terraform_format_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  '${{ github.ref }}'
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials Develop
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_D }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_D }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_D }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: |
          cd environments/dev
          terraform plan 
       
  terraform_plan_test:
    name: Terraform Plan Test
    needs: terraform_format_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  '${{ github.ref }}'
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials Test
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_T }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_T }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_T }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: |
          cd environments/dev
          terraform plan  

  terraform_plan_stage:
    name: Terraform Plan Stage
    needs: terraform_format_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  '${{ github.ref }}'
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials Stage
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_S }}

      - name: Configure AWS Credentials Production
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_S }}
   
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: |
          cd environments/dev
          terraform plan  

  terraform_plan_production:
    name: Terraform Plan Production
    needs: terraform_format_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  '${{ github.ref }}'
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials Production
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_P }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_P }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_P }}
   
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: |
          cd environments/${{github.event.inputs.env}}
          terraform plan      

  